/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DigitalCard: typeof import('./src/components/digitalCard/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ExperienceItem: typeof import('./src/components/experienceItem/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    ProjectCard: typeof import('./src/components/projectCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillItem: typeof import('./src/components/skillItem/index.vue')['default']
  }
}
